Update testconjurmodules.yaml

diff --git a/.github/workflows/testconjurmodules.yaml b/.github/workflows/testconjurmodules.yaml
--- a/.github/workflows/testconjurmodules.yaml
+++ b/.github/workflows/testconjurmodules.yaml
@@ -62,6 +62,11 @@ jobs:
         run: |
           set -x
           echo "Running till here"
+          SESSION_TOKEN=$(cat session_token.txt)
+          if [ -z "$SESSION_TOKEN" ]; then
+            echo "❌ Error: SESSION_TOKEN is empty"
+            exit 1
+          fi
           VAR="data/vault/conjurtest/conjurtest/address"
           SECRET_VALUE=$(curl -s -k --header "Authorization: Token token=\"$SESSION_TOKEN\"" \
           "$CONJUR_URL/secrets/conjur/variable/data%2Fvault%2Fconjurtest%2Fconjurtest%2Faddress")
